version: "3.8"
services:
  validator:
    image: solanalabs/solana:v1.18.26
    command: solana-test-validator --reset --quiet
    ports:
      - "8899:8899"
      - "8900:8900"
    volumes:
      - ./solana-data:/root/.local/share/solana
